package login;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

import management.CarManagementMain;
import others.CostumerMenu;

/*
 *This class is for the Login Proccess 
 */
/**
 *
 * @author YASER
 */
public class Login extends javax.swing.JFrame {
    //initialize varibales 

    String findname, findpass;
    Date date = new Date();

    /**
     * Creates new form login
     */
    public Login() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        newuserButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        passwordPasswordField = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Luxury Cars");
        setMinimumSize(new java.awt.Dimension(908, 428));
        setPreferredSize(new java.awt.Dimension(908, 428));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Pristina", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Welcome to Luxury Cars Online System!");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 10, 590, 50);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("          Login to Your Account");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 110, 515, 40);

        newuserButton.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        newuserButton.setText("New User? Click Here");
        newuserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newuserButtonActionPerformed(evt);
            }
        });
        getContentPane().add(newuserButton);
        newuserButton.setBounds(509, 320, 300, 31);

        jButton2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        jButton2.setText("Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(380, 170, 229, 31);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 190, 110, 50);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 160, 120, 20);

        usernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(usernameTextField);
        usernameTextField.setBounds(220, 160, 132, 30);

        passwordPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordPasswordFieldActionPerformed(evt);
            }
        });
        getContentPane().add(passwordPasswordField);
        passwordPasswordField.setBounds(220, 200, 130, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wallpaper-bmw-wallpapers-white-minimalist-creative-love.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(-10, -50, 990, 490);

        setSize(new java.awt.Dimension(856, 420));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextFieldActionPerformed

    }//GEN-LAST:event_usernameTextFieldActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //these take the username and password from the Text Fields
        findname = usernameTextField.getText();
        findpass = passwordPasswordField.getText();
        //checks if the name and password are correct
        if (Authentication.login(findname, findpass)) {
            Costumer user = (Costumer) Authentication.getUser(Authentication.getUserList(), findname, findpass);
            this.setVisible(false);
            new CostumerMenu(user).setVisible(true);
        } else if (findname.equals("*saeed*") && findpass.equals("saeed123")) {
            this.setVisible(false);
            new CarManagementMain().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Wrong Username or Password", "Wrong", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void passwordPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordPasswordFieldActionPerformed

    }//GEN-LAST:event_passwordPasswordFieldActionPerformed

    private void newuserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newuserButtonActionPerformed
        this.setVisible(false);
        new NewUser().setVisible(true);
    }//GEN-LAST:event_newuserButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton newuserButton;
    private javax.swing.JPasswordField passwordPasswordField;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables

    /**
     *
     */
}
