package management;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import exceptions.CarAlreadyAddedException;
import exceptions.CarNotAvailableException;
import exceptions.CarNotFoundException;
import exceptions.NotValidCarException;
import others.Main;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author YASER
 */

public class ModifyFoundCar extends javax.swing.JFrame {
 String serial,brand,color,model,size,price,plate;
   private int oldCarSerialNum;
   CarManagement carManagement ;
   /**
     * Creates new form ModifyFoundCar
     */
    String[] brandArray = Main.validProperties.getValidBrands().toArray(new String[Main.validProperties.getValidBrands().size()]);
    String[] colorArray = Main.validProperties.getValidColors().toArray(new String[Main.validProperties.getValidColors().size()]);
    String[] modelArray = Main.validProperties.getValidModels().toArray(new String[Main.validProperties.getValidModels().size()]);
    String[] sizeArray = Main.validProperties.getValidSizes().toArray(new String[Main.validProperties.getValidSizes().size()]);

    public ModifyFoundCar(int oldCarSerialNum) {
        this.oldCarSerialNum =oldCarSerialNum;
        this.carManagement = new CarManagement(Main.carList,Main.validProperties);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        modifyButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        platetxt = new javax.swing.JTextField();
        pricetxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        serialtxt = new javax.swing.JTextField();
        brandComboBox = new javax.swing.JComboBox<>();
        colorComboBox = new javax.swing.JComboBox<>();
        sizeComboBox = new javax.swing.JComboBox<>();
        modelComboBox = new javax.swing.JComboBox<>();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Yu Gothic Light", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Car is Found");

        modifyButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        modifyButton.setText("Modify");
        modifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Plate No:");

        jLabel4.setText("Color:");

        jLabel5.setText("Size:");

        jLabel6.setText("Model:");

        jLabel7.setText("Price:");

        platetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                platetxtActionPerformed(evt);
            }
        });

        jLabel8.setText("Brand:");

        jLabel9.setText("Serial No:");

        serialtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serialtxtActionPerformed(evt);
            }
        });

        brandComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(brandArray));

        colorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(colorArray));

        sizeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(sizeArray));

        modelComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(modelArray));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pricetxt)
                            .addComponent(modelComboBox, 0, 205, Short.MAX_VALUE)
                            .addComponent(sizeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(colorComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(27, 27, 27))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(27, 27, 27)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(platetxt)
                            .addComponent(serialtxt)
                            .addComponent(brandComboBox, 0, 205, Short.MAX_VALUE))))
                .addGap(72, 72, 72))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(serialtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(brandComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(platetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(colorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(sizeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(modelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(pricetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        backButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(125, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(modifyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modifyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(631, 504));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void modifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyButtonActionPerformed
        serial = serialtxt.getText();
        brand = brandComboBox.getSelectedItem().toString();
        color = colorComboBox.getSelectedItem().toString();
        model = modelComboBox.getSelectedItem().toString();
        size = sizeComboBox.getSelectedItem().toString();
        price = pricetxt.getText();
        plate = platetxt.getText();

        try {
            int serialNum = Integer.parseInt(serial);
            double priceNum = Double.parseDouble(price);
            if (serial.equals("") || brand.equals("") || color.equals("") || model.equals("") || size.equals("") || price.equals("") || plate.equals("")) {
                JOptionPane.showMessageDialog(null, "Please Fill Up All The Information", "Not Filled Proprly", JOptionPane.ERROR_MESSAGE);
            } else {
                if (carManagement.getValidCarProperties().isValidBrand(brand)) {
                    if (carManagement.getValidCarProperties().isValidColor(color)) {
                        if (carManagement.getValidCarProperties().isValidModel(model)) {
                            if (carManagement.getValidCarProperties().isValidSize(size)) {
                                  carManagement.modifyCar(oldCarSerialNum ,new Car(serialNum, brand, plate, color, size, model, priceNum));
                                JOptionPane.showMessageDialog(null, "Car Has Been Modified Succecfully", "Car is Modified", JOptionPane.INFORMATION_MESSAGE);
                                this.setVisible(false);
                            } else {
                                JOptionPane.showMessageDialog(null, "This is Not a Registered Size", "Already Used", JOptionPane.ERROR_MESSAGE);
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "This is Not a Registered Model", "Already Used", JOptionPane.ERROR_MESSAGE);
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "This is Not a Registered Color", "Already Used", JOptionPane.ERROR_MESSAGE);
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "This is Not a Registered Brand", "Already Used", JOptionPane.ERROR_MESSAGE);
                }

            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please Enter a Number", "Not a Number", JOptionPane.ERROR_MESSAGE);
        } catch (CarAlreadyAddedException ex) {
            JOptionPane.showMessageDialog(null, "The Serial Number Has Been Used Before!", "Serial Number Has Been Used", JOptionPane.ERROR_MESSAGE);
        } catch (NotValidCarException ex) {
            JOptionPane.showMessageDialog(null, "Not Valid Car Properties!, Please Check The Properties Again", "Not Valid Car Properties", JOptionPane.ERROR_MESSAGE);
        } catch (CarNotFoundException ex) {
         JOptionPane.showMessageDialog(null, "Car Not Found", "Car Not Found", JOptionPane.ERROR_MESSAGE);
     } catch (CarNotAvailableException ex) {
         JOptionPane.showMessageDialog(null, "Cannot Be Edited! The Car Is Rented Right Now And Cannot Be Edited", "Cannot Be Edited", JOptionPane.ERROR_MESSAGE);
     }
        
        //else JOptionPane.showMessageDialog(null,"Your Password or Username is Incorrect","Passwords or Username not Matching",JOptionPane.ERROR_MESSAGE);

    }//GEN-LAST:event_modifyButtonActionPerformed

    private void platetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_platetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_platetxtActionPerformed

    private void serialtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serialtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serialtxtActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    public javax.swing.JComboBox<String> brandComboBox;
    public javax.swing.JComboBox<String> colorComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JComboBox<String> modelComboBox;
    private javax.swing.JButton modifyButton;
    public javax.swing.JTextField platetxt;
    public javax.swing.JTextField pricetxt;
    public javax.swing.JTextField serialtxt;
    public javax.swing.JComboBox<String> sizeComboBox;
    // End of variables declaration//GEN-END:variables
}
