package rental;

import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import login.Costumer;
import management.CarRentalModify;
import others.CostumerMenu;
import rental.PaymentReserved;
import rental.Reservation;

/*
 * This class activate when the costumer would have to pay the difference between the old date and the new date for the rental
 */
/**
 *
 * @author YASER
 */
public class ChoosePaymentReserved extends javax.swing.JFrame {
    //initialize variabels

    private static Costumer user;
    private static Reservation reservation;
    private static double cost;
    private static Date endDate;

    /**
     * Creates new form ChoosePayment
     */
    public ChoosePaymentReserved(Costumer user, Reservation reservation, double cost, Date endDate) {
        initComponents();
        this.user = user;
        this.reservation = reservation;
        this.cost = cost;
        checkoutTextField.setText("" + cost);
        this.endDate = endDate;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        checkoutTextField = new javax.swing.JTextField();
        onsiteButton = new javax.swing.JButton();
        onlineButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Rent");

        checkoutTextField.setEditable(false);
        checkoutTextField.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        checkoutTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutTextFieldActionPerformed(evt);
            }
        });

        onsiteButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        onsiteButton.setText("On Site");
        onsiteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onsiteButtonActionPerformed(evt);
            }
        });

        onlineButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        onlineButton.setText("Online");
        onlineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onlineButtonActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Checkout");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("SR");

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jTextField3.setText("Please Choose Payment Method");
        jTextField3.setToolTipText("");
        jTextField3.setBorder(null);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(onsiteButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(onlineButton)
                                .addGap(165, 165, 165))
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(366, 366, 366)
                                                .addComponent(jLabel1))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(374, 374, 374)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel2)
                                                        .addComponent(backButton)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(362, 362, 362)
                                                .addComponent(checkoutTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel3))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(280, 280, 280)
                                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(301, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(checkoutTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(onsiteButton)
                                        .addComponent(onlineButton))
                                .addGap(56, 56, 56)
                                .addComponent(backButton)
                                .addGap(49, 49, 49))
        );

        setSize(new java.awt.Dimension(847, 444));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void checkoutTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutTextFieldActionPerformed

    }//GEN-LAST:event_checkoutTextFieldActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.setVisible(false);
        new CarRentalModify(user, reservation).setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void onsiteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onsiteButtonActionPerformed
        //this message will pop up when the costumer chooses to pay onsite
        JOptionPane.showMessageDialog(null, "You Will Have to Come to Our Company's Branch in a\nMaximum "
                + "of Three Days to Confirm Your Rental or Your Request Will be Canceled.", "Your Request has Been Saved",
                 JOptionPane.INFORMATION_MESSAGE);

        String message = user.modifyReservationmoreCost(reservation, reservation.getCar(), endDate);
        JOptionPane.showMessageDialog(null, message, null, JOptionPane.INFORMATION_MESSAGE);
        this.setVisible(false);
        new CostumerMenu(user).setVisible(true);
    }//GEN-LAST:event_onsiteButtonActionPerformed

    private void onlineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onlineButtonActionPerformed
        this.setVisible(false);
        new PaymentReserved(user, reservation, cost, endDate).setVisible(true);
    }//GEN-LAST:event_onlineButtonActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    public javax.swing.JTextField checkoutTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton onlineButton;
    private javax.swing.JButton onsiteButton;
    // End of variables declaration//GEN-END:variables
}
