package others;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

import login.Costumer;
import login.Login;
import management.Car;
import management.CarRentalManage;
import management.CarSearch;
import rental.CostumerReservation;

/*
This class will reveal the main menu interface for the costumer
 and will allow him to search for a certain car based on the attributes that 
 he choosed for the search proccess.
*/

public class CostumerMenu extends javax.swing.JFrame {
  //initialize variabels
    DefaultTableModel model;
    TableRowSorter<DefaultTableModel> tr;
    ArrayList<Car> carList;
    private static Costumer user;

    public CostumerMenu(Costumer u) {
        initComponents();
        addRowToJtable();
        user = u;
    }

    // this method is for the adding to the table of cars
    public void addRowToJtable() {
        model = (DefaultTableModel) jTable1.getModel();
        carList = CarSearch.search(Main.carList, 0, "", "", "", "", "", true, false, 0, 0);
        Object rowData[] = new Object[7];
        model.setRowCount(0);
        for (int i = 0; i < carList.size(); i++) {
            rowData[0] = carList.get(i).getSerialNum();
            rowData[1] = carList.get(i).getBrand();
            rowData[2] = carList.get(i).getPlateNum();
            rowData[3] = carList.get(i).getColor();
            rowData[4] = carList.get(i).getSize();
            rowData[5] = carList.get(i).getModel();
            rowData[6] = carList.get(i).getCostPerDay();
            model.addRow(rowData);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        searchButton = new javax.swing.JButton();
        label5 = new java.awt.Label();
        label2 = new java.awt.Label();
        brandComboBox = new javax.swing.JComboBox<>();
        colorComboBox = new javax.swing.JComboBox<>();
        sizeComboBox = new javax.swing.JComboBox<>();
        modelComboBox = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        logoutButton = new javax.swing.JButton();
        veiwButton = new javax.swing.JButton();
        contactButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Luxury Cars");
        setPreferredSize(new java.awt.Dimension(908, 428));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        label3.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        label3.setText("Size");

        label4.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        label4.setText("Model");

        searchButton.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        label5.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        label5.setText("Brand");

        label2.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        label2.setText("Color");

        brandComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALL", "TOYOTA", "GMC", "FORD", "BMW" }));
        brandComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandComboBoxActionPerformed(evt);
            }
        });

        colorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALL", "WHITE", "BLACK", "BLUE", "RED", "GREEN", "YELLOW" }));

        sizeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALL", "SUV", "SMALL" }));

        modelComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALL", "2017", "2016", "2015", "2014", "2013", "2012", "2011" }));
        modelComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(brandComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(colorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sizeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brandComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sizeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(colorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(121, 121, 121)
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        logoutButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        veiwButton.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        veiwButton.setText("Veiw My Current Rentals");
        veiwButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veiwButtonActionPerformed(evt);
            }
        });

        contactButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        contactButton.setText("Contact Us");
        contactButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(veiwButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contactButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(veiwButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contactButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial Number", "Brand", "Plate Number", "Color", "Size", "Model", "Cost PerDay"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(400, 400, 400))
        );

        setSize(new java.awt.Dimension(956, 485));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void veiwButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veiwButtonActionPerformed
        this.setVisible(false);
        new CarRentalManage(user).setVisible(true);
    }//GEN-LAST:event_veiwButtonActionPerformed

    private void contactButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactButtonActionPerformed
        this.setVisible(false);
        new Contact(user).setVisible(true);
    }//GEN-LAST:event_contactButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void brandComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandComboBoxActionPerformed

    }//GEN-LAST:event_brandComboBoxActionPerformed

    private void modelComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelComboBoxActionPerformed
        
    }//GEN-LAST:event_modelComboBoxActionPerformed
    //when a car is selected
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int index = jTable1.getSelectedRow();
        model = (DefaultTableModel) jTable1.getModel();
        String serial = model.getValueAt(index, 0).toString();
        String brand = model.getValueAt(index, 1).toString();
        String plate = model.getValueAt(index, 2).toString();
        String color = model.getValueAt(index, 3).toString();
        String size = model.getValueAt(index, 4).toString();
        String model1 = model.getValueAt(index, 5).toString();
        String cost = model.getValueAt(index, 6).toString();
        Car car = CarSearch.search(Main.carList, Integer.parseInt(serial), brand, plate, color, size, model1, null, null, 0, 0).get(0);
        this.setVisible(false);
        new CostumerReservation(user, car).setVisible(true);


    }//GEN-LAST:event_jTable1MouseClicked
    // this button makes the search proccess
    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        //takes the selected items from the comboboxs
        String query1 = brandComboBox.getSelectedItem().toString();
        String query2 = colorComboBox.getSelectedItem().toString();
        String query3 = sizeComboBox.getSelectedItem().toString();
        String query4 = modelComboBox.getSelectedItem().toString();
        if (query1.equals("ALL")) {
            query1 = "";
        }
        if (query2.equals("ALL")) {
            query2 = "";
        }
        if (query3.equals("ALL")) {
            query3 = "";
        }
        if (query4.equals("ALL")) {
            query4 = "";
        }
        model.setRowCount(0);
        CarSearch.search(carList, 0, query1, "", query2, query3, query4, true, false, 0, 0);

        model = (DefaultTableModel) jTable1.getModel();
            
        //this updates the table after the search proccess
        Object rowData[] = new Object[7];
        for (int i = 0; i < CarSearch.search(carList, 0, query1, "", query2, query3, query4, null, null, 0, 0).size(); i++) {
            rowData[0] = CarSearch.search(carList, 0, query1, "", query2, query3, query4, null, null, 0, 0).get(i).getSerialNum();
            rowData[1] = CarSearch.search(carList, 0, query1, "", query2, query3, query4, null, null, 0, 0).get(i).getBrand();
            rowData[2] = CarSearch.search(carList, 0, query1, "", query2, query3, query4, null, null, 0, 0).get(i).getPlateNum();
            rowData[3] = CarSearch.search(carList, 0, query1, "", query2, query3, query4, null, null, 0, 0).get(i).getColor();
            rowData[4] = CarSearch.search(carList, 0, query1, "", query2, query3, query4, null, null, 0, 0).get(i).getSize();
            rowData[5] = CarSearch.search(carList, 0, query1, "", query2, query3, query4, null, null, 0, 0).get(i).getModel();
            rowData[6] = CarSearch.search(carList, 0, query1, "", query2, query3, query4, null, null, 0, 0).get(i).getCostPerDay();
            model.addRow(rowData);

    }//GEN-LAST:event_searchButtonActionPerformed
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> brandComboBox;
    private javax.swing.JComboBox<String> colorComboBox;
    private javax.swing.JButton contactButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private javax.swing.JButton logoutButton;
    private javax.swing.JComboBox<String> modelComboBox;
    private javax.swing.JButton searchButton;
    private javax.swing.JComboBox<String> sizeComboBox;
    private javax.swing.JButton veiwButton;
    // End of variables declaration//GEN-END:variables

}
